services:
  statistics-collector:
    image: statistics-collector
    build:
      context: .
      dockerfile: StatisticsCollector/Dockerfile
    environment:
      - ServerStatisticsConfig__ServerIdentifier=docker-image
      - RabbitMQOptions__HostName=rabbitmq
      - RabbitMQOptions__Port=5672
      - RabbitMQOptions__UserName=root
      - RabbitMQOptions__Password=root
      - RabbitMQOptions__VirtualHost=/
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '8080:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_running" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
  
  
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: base
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongo:27017/
      - ME_CONFIG_BASICAUTH_ENABLED=true
      - ME_CONFIG_BASICAUTH_USERNAME=mongo-express-root
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo-express-root
    depends_on:
      mongo:
        condition: service_healthy